project_id = "lciaiunzacgvvbvcshdh"

[api]
enabled = true
port = 50321
schemas = []
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 50322

[studio]
enabled = true
port = 50323

[inbucket]
enabled = true
port = 50324

# User-facing functions require authentication
# By default, JWT verification is enabled. Only explicitly disable for webhooks.

# Keep public for external webhooks with signature verification
[functions.webhook-handler]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

# Keep public for internal service calls (called by other edge functions)
[functions.save-token-usage]
verify_jwt = false